[profile.default]
src = "src"
test = "test"
script = "script"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
ffi = false

evm_version = "paris"

remappings = [
  "forge-std/=lib/forge-std/src/"
]
